spring.application.name=worktrack-pro-backend

# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/worktrack_db
spring.datasource.username=postgres
spring.datasource.password=071203

# ===============================
# JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=worktrackprosupersecretkey12345678901234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000