spring.application.name=worktrack-pro-backend

# ===============================
# PostgreSQL Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/worktrack_db
spring.datasource.username=postgres
spring.datasource.password=071203

# ===============================
# JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=worktrackprosupersecretkey12345678901234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ===============================
# Kafka Configuration
# ===============================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=worktrack-notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.worktrack.notification.event

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer